name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t lab8 .
      
      - name: Prepare output directory
        run: mkdir -p workspace/output
      
      - name: Run container
        run: |
          docker run --rm -v $(pwd)/workspace/output:/output lab8
          echo "=== Build Log ==="
          cat workspace/output/build_log.txt || echo "Log file not found"
          [ -s workspace/output/build_log.txt ] || echo "Log file is empty"
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: workspace/output/
