name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t lab8 .
      
      - name: Run container and collect logs
        run: |
          mkdir -p workspace/output
          docker run --rm -v $(pwd)/workspace/output:/output lab8
          echo "=== Build Log Content ==="
          cat workspace/output/build_log.txt || echo "No log found"
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: workspace/output/
